- alias: Climate Notifications
  trigger:
    - platform: state
      entity_id: input_number.climate_heat_point
  action:
    - delay:
        seconds: 5
    - service: notify.mobile_app_nathans_iphone
      data_template:
        title: 'Climate Setpoint Change'
        message: 'Climate changed to {{ states("input_number.climate_cool_point") | int }} and {{ states("input_number.climate_heat_point") | int }}.'
