- alias: Freezer Temp High
  trigger:
    platform: numeric_state
    entity_id: sensor.bedroom_temperature
    above: 20
  action:
    service: notify.all_mobile_apps
    data_template:
      title: 'Freezer Temp High!'
      message: 'The freezer temp is indicating {{ states("sensor.bedroom_temperature")}}°F.'
