---

# This automation notifies us if the freezer gets too warm or the door is left
# open. 

- alias: Freezer Temp High
  trigger:
    - platform: numeric_state
      entity_id: sensor.freezer_temperature
      above: 20
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.freezer_temperature
      above: 32
  action:
    service: notify.all_mobile_apps
    data_template:
      title: "Freezer Temp High!"
      message: "The freezer temp is indicating {{ states('sensor.freezer_temperature') }}°F."
- alias: Freezer Door Open
  trigger:
    platform: state
    entity_id: binary_sensor.freezer_door
    to: 'on'
    for:
      minutes: 1
  action:
    - service: notify.all_mobile_apps
      data:
        title: "Freezer Door Open"
        message: "The freezer door has been left open. Current temp {{ states('sensor.freezer_temperature') }}°F."
