- alias: Weather Alert Critical
  trigger:
    platform: state
    entity_id: sensor.fulton_county
  condition:
    - condition: template
      value_template: '{{ state_attr("sensor.fulton_county", "alerts")[0].urgency == "Immediate" }}'
    - condition: template
      value_template: '{{ not trigger.to_state.state | int < trigger.from_state.state | int }}'
    - condition: template
      value_template: '{{ state_attr("sensor.fulton_county", "alerts")[0].event != "Flood Warning" }}'
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
  action:
    - service: notify.all_mobile_apps
      data_template:
        title: >
          {% if state_attr("sensor.fulton_county", "alerts")[0].messageType == "Update" %}
          {{ state_attr("sensor.fulton_county", "alerts")[0].event }} Updated
          {% else %}
          {{ state_attr("sensor.fulton_county", "alerts")[0].event }} for Fulton County!'
          {% endif %}
        message: >
          {{ state_attr("sensor.fulton_county", "alerts")[0].title }}

          {{ state_attr("sensor.fulton_county", "alerts")[0].description }}
        data:
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
            thread-id: 'weather-alert'
    - service: light.turn_on
      entity_id: light.all
- alias: Weather Alert Non Critical
  trigger:
    platform: state
    entity_id: sensor.fulton_county
  condition:
    - condition: template
      value_template: '{{ state_attr("sensor.fulton_county", "alerts")[0].urgency != "Immediate" }}'
    - condition: template
      value_template: '{{ not trigger.to_state.state | int < trigger.from_state.state | int }}'
    - condition: template
      value_template: '{{ trigger.from_state.state != "unavailable" }}'
  action:
    - service: notify.all_mobile_apps
      data_template:
        title: >
          {% if state_attr("sensor.fulton_county", "alerts")[0].messageType == "Update" %}
          {{ state_attr("sensor.fulton_county", "alerts")[0].event }} Updated
          {% else %}
          {{ state_attr("sensor.fulton_county", "alerts")[0].event }} for Fulton County!
          {% endif %}
        data:
          push:
            thread-id: 'weather-alert'
        message: >
          {{ state_attr("sensor.fulton_county", "alerts")[0].title }}

          {{ state_attr("sensor.fulton_county", "alerts")[0].description }}
