- alias: Data at 75%
  trigger:
    platform: numeric_state
    entity_id: sensor.xfinity_usage
    above: 768
  condition:
    condition: state
    entity_id: input_boolean.xfinity_75_notify
    state: 'off'
  action:
    - service: notify.all_mobile_apps
      data:
        title: 'Data Alert'
        message: 'Xfinity Usage is at 75% for this month.'
    - service: input_boolean.turn_on
      entity_id: input_boolean.xfinity_75_notify

- alias: Data at 90%
  trigger:
    platform: numeric_state
    entity_id: sensor.xfinity_usage
    above: 921
  condition:
    condition: state
    entity_id: input_boolean.xfinity_90_notify
    state: 'off'
  action:
    - service: notify.all_mobile_apps
      data:
        title: 'Data Alert'
        message: 'Xfinity Usage is at 90% for this month.'
    - service: input_boolean.turn_on
      entity_id: input_boolean.xfinity_90_notify

- alias: Reset Xfinity Notify
  trigger:
    platform: numeric_state
    entity_id: sensor.xfinity_usage
    below: 768
  condition:
    condition: state
    entity_id: input_boolean.xfinity_75_notify
    state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.xfinity_75_notify
    - service: input_boolean.turn_off
      entity_id: input_boolean.xfinity_90_notify
