stages:
  - test
  - deploy
  - notify

test:
  stage: test
  image: homeassistant/amd64-homeassistant
  before_script:
    - python -m homeassistant --version
    - cp -R ./.test/* ./config
  script:
    - hass --script check_config -c .
