- id: '1606851326918'
  alias: New Automation
  description: ''
  trigger:
  - type: no_vibration
    platform: device
    device_id: acb1b9d3b8fc654c331fa0b6df0a834f
    entity_id: binary_sensor.washer_sensor_vibration
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_nathans_iphone
    data:
      message: washer stopped vibrating
  mode: single
- id: '1606851388243'
  alias: Washer vibration test
  description: ''
  trigger:
  - type: no_vibration
    platform: device
    device_id: acb1b9d3b8fc654c331fa0b6df0a834f
    entity_id: binary_sensor.washer_sensor_vibration
    domain: binary_sensor
  condition: []
  action:
  - service: notify.mobile_app_nathans_iphone
    data:
      message: washer stopped vibrating
  mode: single
