---

- platform: template
  sensors:
    living_room_motion_z:
      friendly_name: "Living Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.living_room_burglar_z', '8') }}"
    kitchen_motion_z:
      friendly_name: "Kitchen Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.kitchen_burglar_z', '8') }}"
    bedroom_motion_z:
      friendly_name: "Bedroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bedroom_burglar_z', '8') }}"
    bathroom_motion_z:
      friendly_name: "Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bathroom_burglar_z', '8') }}"
    atl_departure_delay:
      friendly_name: "ATL Departure Delay"
      value_template: "{{ state_attr('sensor.atl_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.atl_status', 'departure_delay_reason') }}"
    atl_arrival_delay:
      friendly_name: "ATL Arrival Delay"
      value_template: "{{ state_attr('sensor.atl_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.atl_status', 'arrival_delay_reason') }}"
    atl_ground_delay:
      friendly_name: "ATL Ground Delay"
      value_template: "{{ state_attr('sensor.atl_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.atl_status', 'ground_delay_reason') }}"
    atl_ground_stop:
      friendly_name: "ATL Ground Stop"
      value_template: "{{ state_attr('sensor.atl_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.atl_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.atl_status', 'end_time') }}"
    atl_closed:
      friendly_name: "ATL Closed"
      value_template: "{{ state_attr('sensor.atl_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.atl_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.atl_status', 'closure_end') }}"
    dtw_departure_delay:
      friendly_name: "DTW Departure Delay"
      value_template: "{{ state_attr('sensor.dtw_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.dtw_status', 'departure_delay_reason') }}"
    dtw_arrival_delay:
      friendly_name: "DTW Arrival Delay"
      value_template: "{{ state_attr('sensor.dtw_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.dtw_status', 'arrival_delay_reason') }}"
    dtw_ground_delay:
      friendly_name: "DTW Ground Delay"
      value_template: "{{ state_attr('sensor.dtw_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.dtw_status', 'ground_delay_reason') }}"
    dtw_ground_stop:
      friendly_name: "DTW Ground Stop"
      value_template: "{{ state_attr('sensor.dtw_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.dtw_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.dtw_status', 'end_time') }}"
    dtw_closed:
      friendly_name: "DTW Closed"
      value_template: "{{ state_attr('sensor.dtw_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.dtw_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.dtw_status', 'closure_end') }}"
    lga_departure_delay:
      friendly_name: "LGA Departure Delay"
      value_template: "{{ state_attr('sensor.lga_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.lga_status', 'departure_delay_reason') }}"
    lga_arrival_delay:
      friendly_name: "LGA Arrival Delay"
      value_template: "{{ state_attr('sensor.lga_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.lga_status', 'arrival_delay_reason') }}"
    lga_ground_delay:
      friendly_name: "LGA Ground Delay"
      value_template: "{{ state_attr('sensor.lga_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.lga_status', 'ground_delay_reason') }}"
    lga_ground_stop:
      friendly_name: "LGA Ground Stop"
      value_template: "{{ state_attr('sensor.lga_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.lga_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.lga_status', 'end_time') }}"
    lga_closed:
      friendly_name: "LGA Closed"
      value_template: "{{ state_attr('sensor.lga_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.lga_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.lga_status', 'closure_end') }}"
    jfk_departure_delay:
      friendly_name: "JFK Departure Delay"
      value_template: "{{ state_attr('sensor.jfk_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.jfk_status', 'departure_delay_reason') }}"
    jfk_arrival_delay:
      friendly_name: "JFK Arrival Delay"
      value_template: "{{ state_attr('sensor.jfk_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.jfk_status', 'arrival_delay_reason') }}"
    jfk_ground_delay:
      friendly_name: "JFK Ground Delay"
      value_template: "{{ state_attr('sensor.jfk_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.jfk_status', 'ground_delay_reason') }}"
    jfk_ground_stop:
      friendly_name: "JFK Ground Stop"
      value_template: "{{ state_attr('sensor.jfk_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.jfk_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.jfk_status', 'end_time') }}"
    jfk_closed:
      friendly_name: "JFK Closed"
      value_template: "{{ state_attr('sensor.jfk_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.jfk_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.jfk_status', 'closure_end') }}"
    bos_departure_delay:
      friendly_name: "BOS Departure Delay"
      value_template: "{{ state_attr('sensor.bos_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.bos_status', 'departure_delay_reason') }}"
    bos_arrival_delay:
      friendly_name: "BOS Arrival Delay"
      value_template: "{{ state_attr('sensor.bos_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.bos_status', 'arrival_delay_reason') }}"
    bos_ground_delay:
      friendly_name: "BOS Ground Delay"
      value_template: "{{ state_attr('sensor.bos_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.bos_status', 'ground_delay_reason') }}"
    bos_ground_stop:
      friendly_name: "BOS Ground Stop"
      value_template: "{{ state_attr('sensor.bos_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.bos_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.bos_status', 'end_time') }}"
    bos_closed:
      friendly_name: "BOS Closed"
      value_template: "{{ state_attr('sensor.bos_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.bos_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.bos_status', 'closure_end') }}"
    ord_departure_delay:
      friendly_name: "ORD Departure Delay"
      value_template: "{{ state_attr('sensor.ord_status', 'departure_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.ord_status', 'departure_delay_reason') }}"
    ord_arrival_delay:
      friendly_name: "ORD Arrival Delay"
      value_template: "{{ state_attr('sensor.ord_status', 'arrival_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.ord_status', 'arrival_delay_reason') }}"
    ord_ground_delay:
      friendly_name: "ORD Ground Delay"
      value_template: "{{ state_attr('sensor.ord_status', 'ground_delay') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.ord_status', 'ground_delay_reason') }}"
    ord_ground_stop:
      friendly_name: "ORD Ground Stop"
      value_template: "{{ state_attr('sensor.ord_status', 'ground_stop') }}"
      attribute_templates:
        reason: "{{ state_attr('sensor.ord_status', 'ground_stop_reason') }}"
        end: "{{ state_attr('sensor.ord_status', 'end_time') }}"
    ord_closed:
      friendly_name: "ORD Closed"
      value_template: "{{ state_attr('sensor.ord_status', 'closed') }}"
      attribute_templates:
        reason: "{{state_attr('sensor.ord_status', 'closure_reason') }}"
        end: "{{ state_attr('sensor.ord_status', 'closure_end') }}"
    weather_alert:
      friendly_name: Weather Alert
      value_template: "{{ not is_state('sensor.fulton_county', '0') }}"
      device_class: safety
- platform: workday
  country: US
  province: GA
  workdays: [mon, tue, wed, thu]
