- platform: template
  sensors:
    living_room_motion_z:
      friendly_name: "Living Room Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.living_room_burglar_z', '8') }}"
    hallway_motion_z:
      friendly_name: "Hallway Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.hallway_burglar_z', '8') }}"
    bedroom_motion_z:
      friendly_name: "Bedroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bedroom_burglar_z', '8') }}"
    bathroom_motion_z:
      friendly_name: "Bathroom Motion"
      device_class: motion
      value_template: "{{ is_state('sensor.bathroom_burglar_z', '8') }}"
    atl_ground_delay:
      friendly_name: "ATL GDP"
      value_template: "{{ state_attr('sensor.atl_status', 'Ground Delay') }}"
    atl_ground_stop:
      friendly_name: "ATL GS"
      value_template: "{{ state_attr('sensor.atl_status', 'Ground Stop') }}"
    atl_closed:
      friendly_name: "ATL Closed"
      value_template: "{{ state_attr('sensor.atl_status', 'Closed') }}"
    dtw_ground_delay:
      friendly_name: "DTW GDP"
      value_template: "{{ state_attr('sensor.dtw_status', 'Ground Delay') }}"
    dtw_ground_stop:
      friendly_name: "DTW GS"
      value_template: "{{ state_attr('sensor.dtw_status', 'Ground Stop') }}"
    dtw_closed:
      friendly_name: "DTW Closed"
      value_template: "{{ state_attr('sensor.dtw_status', 'Closed') }}"
    lga_ground_delay:
      friendly_name: "LGA GDP"
      value_template: "{{ state_attr('sensor.lga_status', 'Ground Delay') }}"
    lga_ground_stop:
      friendly_name: "LGA GS"
      value_template: "{{ state_attr('sensor.lga_status', 'Ground Stop') }}"
    lga_closed:
      friendly_name: "LGA Closed"
      value_template: "{{ state_attr('sensor.lga_status', 'Closed') }}"
    jfk_ground_delay:
      friendly_name: "JFK GDP"
      value_template: "{{ state_attr('sensor.jfk_status', 'Ground Delay') }}"
    jfk_ground_stop:
      friendly_name: "JFK GS"
      value_template: "{{ state_attr('sensor.jfk_status', 'Ground Stop') }}"
    jfk_closed:
      friendly_name: "JFK Closed"
      value_template: "{{ state_attr('sensor.jfk_status', 'Closed') }}"
    bos_ground_delay:
      friendly_name: "BOS GDP"
      value_template: "{{ state_attr('sensor.bos_status', 'Ground Delay') }}"
    bos_ground_stop:
      friendly_name: "BOS GS"
      value_template: "{{ state_attr('sensor.bos_status', 'Ground Stop') }}"
    bos_closed:
      friendly_name: "BOS Closed"
      value_template: "{{ state_attr('sensor.bos_status', 'Closed') }}"
    ord_ground_delay:
      friendly_name: "ORD GDP"
      value_template: "{{ state_attr('sensor.ord_status', 'Ground Delay') }}"
    ord_ground_stop:
      friendly_name: "ORD GS"
      value_template: "{{ state_attr('sensor.ord_status', 'Ground Stop') }}"
    ord_closed:
      friendly_name: "ORD Closed"
      value_template: "{{ state_attr('sensor.ord_status', 'Closed') }}"
- platform: workday
  country: US
  province: GA
  workdays: [mon, tue, wed, thu]
