homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

default_config:

updater:
  include_used_components: true

discovery:
  ignore:
    - denonavr

http:
  base_url: !secret base_url
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

lovelace:
  mode: yaml

history:
  include:
    domains:
      - device_tracker
      - fan
      - light
      - person
      - sensor
      - sun
    entities:
      - binary_sensor.amcrest_camera_motion_detected
      - binary_sensor.bathroom_motion
      - binary_sensor.bathroom_motion_z
      - binary_sensor.bedroom_motion
      - binary_sensor.bedroom_motion_z
      - binary_sensor.front_door
      - binary_sensor.hallway_motion_z
      - binary_sensor.living_room_motion_z
      - climate.ct_100
      - switch.coffee_maker
      - weather.dark_sky
  exclude:
    entities:
      - sensor.atl_end_time
      - sensor.bathroom_alarm_level_z
      - sensor.bathroom_alarm_type_z
      - sensor.bathroom_burglar_z
      - sensor.bathroom_sourcenodeid_z
      - sensor.bedroom_alarm_level_z
      - sensor.bedroom_alarm_type_z
      - sensor.bedroom_burglar_z
      - sensor.bedroom_power_management_z
      - sensor.bedroom_sourcenodeid_z
      - sensor.bedroom_system_z
      - sensor.bos_end_time
      - sensor.date
      - sensor.dtw_end_time
      - sensor.ecolink_door_window_sensor_access_control
      - sensor.ecolink_door_window_sensor_alarm_level
      - sensor.ecolink_door_window_sensor_alarm_type
      - sensor.ecolink_door_window_sensor_burglar
      - sensor.ecolink_door_window_sensor_power_management
      - sensor.ecolink_door_window_sensor_sourcenodeid
      - sensor.hacs
      - sensor.hallway_alarm_level_z
      - sensor.hallway_alarm_type_z
      - sensor.hallway_burglar_z
      - sensor.hallway_power_management_z
      - sensor.hallway_sourcenodeid_z
      - sensor.jfk_end_time
      - sensor.lga_end_time
      - sensor.living_room_alarm_type_z
      - sensor.living_room_burglar_z
      - sensor.living_room_sourcenodeid_z
      - sensor.living_room_system_z
      - sensor.nathan_ipad_bssid
      - sensor.nathan_ipad_sim_1
      - sensor.nathan_iphone_bssid
      - sensor.nathan_iphone_sim_1
      - sensor.npr_news_scrape
      - sensor.ord_end_time
      - sensor.outdoor_temperature_stats
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_battery_level
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_battery_level_2
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_indicator_3
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_indicator_4
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_relative_humidity_2
      - sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_temperature_2
      - sensor.sara_iphone_bssid
      - sensor.sara_iphone_sim_1
      - sensor.sara_iphone_ssid
      - sensor.time
      - sensor.time_date
      - sensor.time_utc


influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

recorder:
  purge_keep_days: 2
  purge_interval: 1

zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_key
  polling_interval: 30000
  device_config:
    light.island_dimmer:
      refresh_value: true
      delay: 3

mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_user1
  password: !secret mqtt_pass1
  client_id: home-assistant

mobile_app:

notify:
  - platform: rest
    name: discord_webhook
    method: POST
    message_param_name: content
    title_param_name: username
    data:
      username: Home Assistant
    resource: !secret discord_webhook_url
  - platform: group
    name: all_mobile_apps
    services:
      - service: mobile_app_nathans_iphone
      - service: mobile_app_saras_iphone

weather:
  - platform: darksky
    api_key: !secret darksky_api

camera:
  - platform: nwsradar
    station: FFC

amcrest:
  host: !secret amcrest_host
  username: !secret amcrest_user
  password: !secret amcrest_pass
  binary_sensors:
    - motion_detected

heos:
  host: !secret marantz_ip

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: mpd
    name: volumio_mpd
    host: !secret volumio_ip

fan:
  - platform: template
    fans:
      living_room:
        friendly_name: Living Room Fan
        value_template: "{{ states('switch.living_room_ceiling_fan') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.living_room_ceiling_fan
        turn_off:
          service: switch.turn_off
          entity_id: switch.living_room_ceiling_fan

tts:
  - platform: google_translate
    base_url: !secret internal_ip

wemo:
  static:
    - !secret wemo_coffee_switch_ip

hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: false

automation: !include_dir_merge_list automation
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
light: !include light.yaml
scene: !include scene.yaml
script: !include scripts.yaml
group: !include group.yaml
