default_config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 3

lovelace:
  mode: yaml

zone:
  - name: ATL
    latitude: !secret atl_latitude
    longitude: !secret atl_longitude
    icon: mdi:airplane

zwave:
  usb_path: /dev/ttyACM1
  network_key: !secret zwave_key

mobile_app:

ios:

amcrest:
  host: !secret amcrest_host
  username: !secret amcrest_user
  password: !secret amcrest_pass
  binary_sensors:
    - motion_detected

automation: !include_dir_merge_list automation
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensor.yaml
customize: !include customize.yaml
