default_config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

zwave:
  network_key: !secret zwave_key

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
