default_config:

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

mobile_app:

ios:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
