---

- platform: switch
  name: Kitchen Lights
  entity_id: switch.kitchen_lights
- platform: switch
  name: Hallway Light
  entity_id: switch.hallway_light
- platform: switch
  name: Bedroom Light
  entity_id: switch.bedroom_light
- platform: switch
  name: Closet Light
  entity_id: switch.shelly1_c487e3_relay_0
- platform: switch
  name: Balcony Lights
  entity_id: switch.shelly1_b90377_relay_0
- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_light_1
    - light.bathroom_light_2
    - light.bathroom_light_3
- platform: group
  name: all
  entities:
    - light.bathroom_lights
    - light.bedroom_lamp
    - light.bedroom_light
    - light.couch
    - light.hallway_light
    - light.island_dimmer
    - light.kitchen_lights
    - light.living_room_lamp
    - light.bedroom_led
    - light.closet_light
    - light.balcony_lights
    - light.kitchen_stove_leds
    - light.kitchen_sink_leds
