- platform: switch
  name: Kitchen Lights
  entity_id: switch.kitchen_lights
- platform: switch
  name: Hallway Light
  entity_id: switch.hallway_light
- platform: switch
  name: Bedroom Light
  entity_id: switch.bedroom_light
- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_light_1
    - light.bathroom_light_2
    - light.bathroom_light_3
