- platform: template
  sensors:
    hvac_action:
      friendly_name: HVAC Action
      value_template: '{{ state_attr("climate.ct_100_cool", "hvac_action") }}'
- platform: mqtt
  name: "ATL Delay"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "ATL Ground Delay"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "ATL Ground Stop"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "ATL End Time"
  state_topic: "delays/ATL"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "DTW Delay"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "DTW Ground Delay"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "DTW Ground Stop"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "DTW End Time"
  state_topic: "delays/DTW"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "LGA Delay"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "LGA Ground Delay"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "LGA Ground Stop"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "LGA End Time"
  state_topic: "delays/LGA"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "JFK Delay"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "JFK Ground Delay"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "JFK Ground Stop"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "JFK End Time"
  state_topic: "delays/JFK"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "BOS Delay"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "BOS Ground Delay"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "BOS Ground Stop"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "BOS End Time"
  state_topic: "delays/BOS"
  value_template: "{{ value_json.EndTime }}"
- platform: mqtt
  name: "ORD Delay"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.Delay }}"
- platform: mqtt
  name: "ORD Ground Delay"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.GroundDelay }}"
- platform: mqtt
  name: "ORD Ground Stop"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.GroundStop }}"
- platform: mqtt
  name: "ORD End Time"
  state_topic: "delays/ORD"
  value_template: "{{ value_json.EndTime }}"
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'time_date'
    - 'time_utc'
