title: Home
views:

  - path: default_view
    title: Home
    badges:
      - person.nathan
      - sensor.bedroom_light
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.bathroom_light
      - sensor.bathroom_humidity
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
      - binary_sensor.front_door
    cards:
      - type: entities
        entities:
          - light.bedroom_sensor_status
          - light.bathroom_sensor_status
        title: Light
      - type: entities
        entities:
          - switch.coffee_maker
        title: Switch
      - type: weather-forecast
        entity: weather.home

  - path: climate
    title: Climate
    icon: mdi:air-conditioner
    badges:
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
    cards:
      - type: thermostat
        entity: climate.ct_100_heat
      - type: thermostat
        entity: climate.ct_100_cool
      - type: entities
        entities:
          - input_number.climate_heat_point
          - input_number.climate_cool_point
          - input_number.climate_heat_default
          - input_number.climate_cool_default
          - input_number.climate_away_offset
          - input_number.climate_trip_offset
          - input_number.climate_sleep_offset

  - path: config
    title: config
    icon: mdi:settings
    cards:
      - type: entities
        title: Status
        entities:
          - input_boolean.trip_mode
      - type: entities
        title: Notification Automations
        entities:
          - automation.front_door
          - automation.climate_notifications
      - type: entities
        title: Climate Automations
        entities:
          - automation.climate_set_cool
          - automation.climate_set_heat
          - automation.climate_set_home
          - automation.climate_set_away
          - automation.climate_set_trip
      - type: entities:
        title: Other Automations
        entities:
          - automation.toggle_trip_mode
