title: Home
views:
  - path: default_view
    title: Home
    badges:
      - person.nathan
      - sensor.bedroom_light
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.bathroom_light
      - sensor.bathroom_humidity
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
      - binary_sensor.front_door
    cards:
      - type: thermostat
        entity: climate.ct_100_heat
      - type: thermostat
        entity: climate.ct_100_cool
      - type: entities
        entities:
          - light.bedroom_sensor_status
          - light.bathroom_sensor_status
        title: Light
      - type: entities
        entities:
          - switch.coffee_maker
        title: Switch
      - type: weather-forecast
        entity: weather.home
  - path: config
    title: config
    icon: mdi:settings
    cards:
      type: entities
      entity: light.bedroom_sensor_status
