title: Home
views:
  - path: default_view
    title: Home
    badges:
      - person.nathan
      - sensor.bedroom_light
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.bathroom_light
      - sensor.bathroom_humidity
      - sensor.thermostat_temperature
      - sensor.thermostat_humidity
    cards:
      - type: thermostat
        entity: >-
          climate.thermostat.heat
      - type: thermostat
        entity: >-
          climate.thermostat.cool
      - type: entities
        entities:
          - light.bedroom_sensor_status
          - light.bathroom_sensor_status
        title: Light
      - type: entities
        entities:
          - switch.coffee_maker
        title: Switch
      - type: weather-forecast
        entity: weather.home
