title: Home
views:

  - path: default_view
    title: Home
    badges:
      - person.nathan
      - sensor.bedroom_light
      - sensor.bedroom_humidity
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      - sensor.bathroom_light
      - sensor.bathroom_humidity
      - binary_sensor.front_door
      - binary_sensor.amcrest_camera_motion_detected
    cards:
      - type: entities
        entities:
          - light.bedroom_sensor_status
          - light.bathroom_sensor_status
        title: Light
      - type: entities
        entities:
          - switch.coffee_maker
        title: Switch
      - type: weather-forecast
        entity: weather.home
      - type: picture-entity
        entity: camera.amcrest_camera

  - path: living_room
    title: Living Room
    cards:
      - type: entities
        entities:
          - light.kitchen_lights
          - light.island_dimmer
          - light.hallway_light
      - type: media-control
        entity: media_player.marantz_sr5012

  - path: bedroom
    title: Bedroom
    cards:
      - type: entities
        entities:
          - light.bedroom_light

  - path: climate
    title: Climate
    icon: mdi:air-conditioner
    badges:
      - sensor.ct_100_temperature
      - sensor.ct_100_humidity
      - sensor.hvac_action
    cards:
      - type: thermostat
        entity: climate.ct_100_heat
      - type: thermostat
        entity: climate.ct_100_cool
      - type: entities
        entities:
          - input_number.climate_heat_point
          - input_number.climate_cool_point
          - input_number.climate_heat_default
          - input_number.climate_cool_default
          - input_number.climate_away_offset
          - input_number.climate_trip_offset
          - input_number.climate_sleep_offset

  - path: delays
    title: Delays
    icon: mdi:airplane
    cards:
      - type: entities
        title: ATL Delays
        entities:
          - sensor.dtw_delay
          - sensor.atl_ground_delay
          - sensor.atl_ground_stop
          - sensor.atl_end_time
          - input_boolean.atl_notify
        show_header_toggle: false
      - type: entities
        title: DTW Delays
        entities:
          - sensor.dtw_delay
          - sensor.dtw_ground_delay
          - sensor.dtw_ground_stop
          - sensor.dtw_end_time
          - input_boolean.dtw_notify
        show_header_toggle: false
      - type: entities
        title: LGA Delays
        entities:
          - sensor.lga_delay
          - sensor.lga_ground_delay
          - sensor.lga_ground_stop
          - sensor.lga_end_time
          - input_boolean.lga_notify
        show_header_toggle: false
      - type: entities
        title: JFK Delays
        entities:
          - sensor.jfk_delay
          - sensor.jfk_ground_delay
          - sensor.jfk_ground_stop
          - sensor.jfk_end_time
          - input_boolean.jfk_notify
        show_header_toggle: false
      - type: entities
        title: BOS Delays
        entities:
          - sensor.bos_delay
          - sensor.bos_ground_delay
          - sensor.bos_ground_stop
          - sensor.bos_end_time
          - input_boolean.bos_notify
        show_header_toggle: false
      - type: entities
        title: ORD Delays
        entities:
          - sensor.ord_delay
          - sensor.ord_ground_delay
          - sensor.ord_ground_stop
          - sensor.ord_end_time
          - input_boolean.ord_notify
        show_header_toggle: false

  - path: config
    title: config
    icon: mdi:settings
    cards:
      - type: entities
        title: Status
        entities:
          - input_boolean.trip_mode
      - type: entities
        title: Notification Automations
        entities:
          - automation.front_door
          - automation.climate_notifications
          - automation.atl_ground_delay
          - automation.atl_ground_stop
          - automation.atl_gs_cancel
          - automation.dtw_ground_delay
          - automation.dtw_ground_stop
          - automation.dtw_gs_cancel
          - automation.lga_ground_delay
          - automation.lga_ground_stop
          - automation.lga_gs_cancel
          - automation.jfk_ground_delay
          - automation.jfk_ground_stop
          - automation.jfk_gs_cancel
          - automation.bos_ground_delay
          - automation.bos_ground_stop
          - automation.bos_gs_cancel
          - automation.ord_ground_delay
          - automation.ord_ground_stop
          - automation.ord_gs_cancel
      - type: entities
        title: Light Automations
        entities:
          - automation.away_lights
          - automation.home_lights
      - type: entities
        title: Climate Automations
        entities:
          - automation.climate_set_cool
          - automation.climate_set_heat
          - automation.climate_set_home
          - automation.climate_set_away
          - automation.climate_set_trip
      - type: entities
        title: Other Automations
        entities:
          - automation.toggle_trip_mode
      - type: entities
        entities:
          - script.adam_mp3
