---

title: Mobile
views:

  - path: default_view
    title: Home
    cards:
      - type: conditional
        conditions:
          - entity: sensor.fulton_county
            state_not: '0'
        card:
          type: markdown
          content: >
            ## Active Weather Alerts:

            {% for alert in state_attr("sensor.fulton_county", "alerts") %}
              {{ alert.event }}
            {%- endfor %}
      - type: custom:stack-in-card
        title: Lights and Switches
        cards:
          - type: button
            entity: light.all
            name: All Lights Off
            tap_action:
              action: call-service
              service: light.turn_off
              service_data:
                entity_id: light.all
          - type: entities
            entities:
              - type: divider
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.kitchen_lights
                name: Kitchen
              - type: button
                entity: fan.living_room
                name: Fan
          - type: entities
            entities:
              - type: divider
          - type: custom:light-brightness-preset-row
            entity: light.island_dimmer
            name: Island
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
          - type: custom:light-brightness-preset-row
            entity: light.living_room_lamp
            name: Lamp
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
          - type: custom:light-brightness-preset-row
            entity: light.couch
            name: Couch
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
          - type: entities
            entities:
              - type: divider
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.hallway_light
                name: Hallway
              - type: button
                entity: light.bedroom_light
                name: Bedroom
          - type: entities
            entities:
              - type: divider
          - type: custom:light-brightness-preset-row
            entity: light.bedroom_lamp
            name: Bed Lamp
            customSetpoints: true
            LowBrightness: 50
            MedBrightness: 128
            HiBrightness: 255
