sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_temperature_3:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_cooling_1:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_dry_air:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_dry_air_2:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_furnace:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_furnace_2:
  ignored: true
  polling_intensity: 0
climate.radio_thermostat_company_of_america_ct100_plus_thermostat_heating_1:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_relative_humidity:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_relative_humidity_2:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_temperature:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_temperature_2:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_indicator_4:
  ignored: true
  polling_intensity: 0
sensor.radio_thermostat_company_of_america_ct100_plus_thermostat_indicator_3:
  ignored: true
  polling_intensity: 0
climate.ct_100_cool:
  ignored: false
  polling_intensity: 1
