- alias: Away Lights
  trigger:
    platform: state
    entity_id: person.nathan
    to: 'not_home'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_switches
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_fans
