- alias: Away Lights
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights
    - service: homeassistant.turn_off
      data:
        entity_id: switch.coffee_maker
    - service: homeassistant.turn_off
      data:
        entity_id: fan.living_room
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleep_mode
    - service: fan.turn_off
      entity_id: fan.living_room
