---

# This automation turns off all lights as well as the coffee maker, fan, and
# sleep mode when we leave home.

- alias: Away Lights
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'not_home'
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.all
    - service: homeassistant.turn_off
      data:
        entity_id: switch.coffee_maker
    - service: input_boolean.turn_off
      entity_id: input_boolean.sleep_mode
    - service: fan.turn_off
      entity_id: fan.living_room
