---

- alias: Home Lights
  trigger:
    platform: state
    entity_id: group.home_devices
    to: 'home'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    service: scene.turn_on
    entity_id: scene.welcome_home
