- alias: Night Lights
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_z
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.island_dimmer
        brightness: 8
    - delay:
        milliseconds: 50
    - service: light.turn_on
      data:
        entity_id: light.island_dimmer
        brightness: 1
- alias: Night Lights Off
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion_z
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.island_dimmer
- alias: Night Lights Off in Morning
  trigger:
    platform: numeric_state
    entity_id: sensor.living_room_luminance_z
    above: 50
  condition:
    condition: template
    value_template: "{{ state_attr('light.island_dimmer', 'brightness') < 10 }}"
  action:
    service: light.turn_off
    entity_id: light.island_dimmer
