- alias: Lights at Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: template
      value_template: "{{ not is_state('media_player.apple_tv', 'playing') }}"
  action:
    service: scene.turn_on
    entity_id: scene.normal_lights
- alias: Lights at Sunset TV On
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: template
      value_template: "{{ is_state('media_player.apple_tv', 'playing') }}"
  action:
    service: scene.turn_on
    entity_id: scene.tv_lights
