---

# This turns some lights on at sunset, which lights depends on whether or not
# we are watching TV.

- alias: Lights at Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: template
      value_template: "{{ not is_state('media_player.apple_tv', 'playing') }}"
  action:
    service: scene.turn_on
    entity_id: scene.normal_lights

- alias: Lights at Sunset TV On
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: template
      value_template: "{{ is_state('media_player.apple_tv', 'playing') }}"
  action:
    service: scene.turn_on
    entity_id: scene.tv_lights

- alias: Balcony Lights On at Sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    service: light.turn_on
    entity_id: light.balcony_lights

- alias: Balcony Lights Off at 10 PM
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: light.turn_off
    entity_id: light.balcony_lights
