---

# This turns some lights on at sunset, which lights depends on whether or not
# we are watching TV.

- alias: Lights at Sunset
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: 'elevation'
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: not
      conditions:
        - condition: state
          entity_id: media_player.apple_tv
          state: 'playing'
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.normal_lights

- alias: Lights at Sunset TV On
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    attribute: 'elevation'
    below: 5.0
  condition:
    - condition: state
      entity_id: group.home_devices
      state: 'home'
    - condition: template
      value_template: "{{ is_state('media_player.apple_tv', 'playing') }}"
    - condition: state
      entity_id: input_boolean.dumb_mode
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.tv_lights
