---

- alias: Climate Turn Off
  trigger:
    platform: state
    entity_id: input_boolean.window_open
    to: 'on'
    for:
      seconds: 30
  action:
    service: climate.turn_off
    entity_id: climate.thermostat
- alias: Climate Change Mode
  trigger:
    - platform: state
      entity_id: input_boolean.window_open
      to: 'off'
      for:
        seconds: 30
  condition:
    condition: state
    entity_id: input_boolean.window_open
    state: 'off'
  action:
    service: climate.set_hvac_mode
    data_template:
      entity_id: climate.thermostat
      hvac_mode: 'heat_cool'
