---

# This is an automation run once a day to record the value of how much the
# HVAC runs and the average temperature. Used for long term data analysis
# through InfluxDB.

- alias: Record AC Cool Time
  trigger:
    platform: time
    at: "23:59:45"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.previous_day_ac_cool
      value: "{{ states('sensor.ac_cool_today') }}"
- alias: Record AC Heat Time
  trigger:
    platform: time
    at: "23:59:45"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.previous_day_ac_heat
      value: "{{ states('sensor.ac_heat_today') }}"
- alias: Record Average
  trigger:
    platform: time
    at: "23:59:45"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.previous_day_average_temp
      value: "{{ states('sensor.outdoor_temperature_stats') }}"
