- alias: Climate Set Cool
  trigger:
    platform: state
    entity_id: input_number.climate_cool_point
  action:
    service: climate.set_temperature
    data_template:
      entity_id: climate.ct_100_cool
      temperature: '{{ trigger.to_state.state | int }}'
- alias: Climate Set Heat
  trigger:
    platform: state
    entity_id: input_number.climate_heat_point
  action:
    service: climate.set_temperature
    data_template:
      entity_id: climate.ct_100_heat
      temperature: '{{ trigger.to_state.state | int }}'
