---

- alias: Climate Set Point
  trigger:
    - platform: state
      entity_id: input_number.climate_cool_point
    - platform: state
      entity_id: input_number.climate_heat_point
    - platform: state
      entity_id: input_boolean.climate_override
      to: 'on'
      for:
        hours: 1
    - platform: state
      entity_id: climate.thermostat
      to: 'heat_cool'
  condition:
    condition: template
    value_template: '{{ not is_state("climate.thermostat", "off") }}'
  action:
    - delay: '00:00:02'
    - service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat
        target_temp_high: '{{ states("input_number.climate_cool_point") }}'
        target_temp_low: '{{ states("input_number.climate_heat_point") }}'
    - service: input_boolean.turn_off
      entity_id: input_boolean.climate_override
