---

- alias: Christmas Lights On
  trigger:
    - platform: state
      entity_id: group.home_devices
      to: 'home'
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree

- alias: Christmas Lights Off
  trigger:
    - platform: state
      entity_id: group.home_devices
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.dumb_mode
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.christmas_tree
