---

# These automations calculate the time for Nathan to drive to work based on
# what time he needs to be there, and then notifies him of when that time is
# 15 and 5 minutes away.

- alias: Time to Leave
  trigger:
    - platform: state
      entity_id: sensor.travel_home_to_atl
    - platform: template
      value_template: >
        {% if state_attr('calendar.report', 'start_time') %}
        {{ state_attr('calendar.report', 'start_time')|as_timestamp() - now()|as_timestamp() == 21600 }}
        {% else %}
        False
        {% endif %}
  condition:
    - condition: template
      value_template: >
        {% if state_attr('calendar.report', 'start_time') %}
        {{ state_attr('calendar.report', 'start_time')|as_timestamp() - now()|as_timestamp() < 43200 }}"
        {% else %}
        False
        {% endif %}
    - condition: state
      entity_id: person.nathan
      state: 'home'
  action:
    service: input_datetime.set_datetime
    data_template:
      entity_id: input_datetime.time_to_leave
      time: >
        {% set stamp = (state_attr('calendar.report', 'start_time')|as_timestamp() - (states('sensor.travel_home_to_atl')|round(0, 'ceil')|int() * 60) - 1800) %}
        {% set rounddown = stamp - (stamp % 600) %}
        {{ rounddown|timestamp_custom('%H:%M:%S') }}
- alias: Notify to Leave
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == ((state_attr('input_datetime.time_to_leave', 'timestamp') - 900) | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: template
      value_template: "{{ state_attr('calendar.report', 'start_time')|as_timestamp() - now()|as_timestamp() < 43200 }}"
    - condition: state
      entity_id: person.nathan
      state: 'home'
  action:
    service: notify.mobile_app_nathans_iphone
    data_template:
      title: 'Time to Leave!'
      message: "Leave at {{ state_attr('input_datetime.time_to_leave', 'timestamp') | timestamp_custom('%-I:%M %p', False) }} to arrive on time. Take {{ state_attr('sensor.travel_home_to_atl', 'route') }}."
- alias: Leave Now
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == ((state_attr('input_datetime.time_to_leave', 'timestamp') - 300) | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    - condition: template
      value_template: "{{ state_attr('calendar.report', 'start_time')|as_timestamp() - now()|as_timestamp() < 43200 }}"
    - condition: state
      entity_id: person.nathan
      state: 'home'
    - condition: not
      conditions:
        condition: state
        entity_id: sensor.nathans_iphone_activity
        state: 'Automotive'
  action:
    service: notify.mobile_app_nathans_iphone
    data_template:
      title: 'Leave Now!'
      message: "Leave at {{ state_attr('input_datetime.time_to_leave', 'timestamp') | timestamp_custom('%-I:%M %p', False) }} to arrive on time. Take {{ state_attr('sensor.travel_home_to_atl', 'route') }}."
