---

# These automations toggle an input boolean when windows or doors are opened or
# closed.

- alias: Window or Door Open
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_1
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_2
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_3
      to: 'on'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.window_open

# This automation has triggers for all of the binary sensors as well as
# conditions for all to ensure that it triggers any time one is closed but only
# runs when all are closed.

- alias: Window or Door Closed
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_window_1
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_window_2
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_window_3
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.front_door
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedroom_window_1
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedroom_window_2
      state: 'off'
    - condition: state
      entity_id: binary_sensor.bedroom_window_3
      state: 'off'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.window_open
