esphome:
  name: bedroom_window
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifipw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Window Fallback Hotspot"
    password: "e0dWNfNygGEw"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: "Bedroom Window 1"
    device_class: window
  - platform: gpio
    pin: 
      number: D6
      mode: INPUT_PULLUP
    name: "Bedroom Window 2"
    device_class: window
  - platform: gpio
    pin: 
      number: D7
      mode: INPUT_PULLUP
    name: "Bedroom Window 3"
    device_class: window