---

esphome:
  name: fridge_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifipw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fridge Sensor Fallback Hotspot"
    password: "JpckVQVQ1H7D"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

dallas:
  pin: D1

sensor:
  - platform: dallas
    address: 0x86000008E30E1728
    name: "Fridge Temperature"

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: "Fridge Door"
    device_class: door
