esphome:
  name: fridge_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifipw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fridge Sensor Fallback Hotspot"
    password: "xnvIDYhd4aaX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: esp8266_pwm
    pin: D2
    id: redgpio
    inverted: True
  - platform: esp8266_pwm
    pin: D3
    id: greengpio
    inverted: True
  - platform: esp8266_pwm
    pin: D4
    id: bluegpio
    inverted: True
    
light:
  - platform: rgb
    name: Freezer LED
    id: freezer_led
    red: redgpio
    green: greengpio
    blue: bluegpio

dallas:
  pin: D1
  
sensor: 
  - platform: dallas
    address: 0x91000008E3884528
    name: Freezer Temperature
    
binary_sensor: 
  - platform: gpio
    pin: 
      number: D5
      mode: INPUT_PULLUP
    name: Fridge Door
    device_class: door
    on_press:
      then:
        - light.turn_on:
            id: freezer_led
            red: 1.0
            green: 1.0
            blue: 0.0
    on_release:
      then:
        - light.turn_on:
            id: freezer_led
            green: 1.0
            red: 0.0
            blue: 0.0
    
