---

esphome:
  name: test
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !secret ssid
  password: !secret wifipw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "ceeZSEGJ0OCV"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: 34
    name: "Solar Battery Voltage"
